# Generated by Django 5.0.6 on 2024-06-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image_matieres_niveau_alter_logo_ecole_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointeur_Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=100)),
                ('select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.epreuve')),
            ],
        ),
    ]
