# Generated by Django 5.0.6 on 2024-06-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_pointeur_epreuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='photo_epreuve',
            field=models.ImageField(null=True, upload_to='photo_epreuve'),
        ),
    ]
