# Generated by Django 5.0.6 on 2024-07-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_correction_image_apercu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='image_apercu',
        ),
    ]
