# Generated by Django 5.0.6 on 2024-07-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_correction_image_apercu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pointeur_Epreuve',
        ),
    ]
