# Generated by Django 5.0.6 on 2024-07-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_pointeur_epreuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='epreuve',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
