# Generated by Django 5.0.6 on 2024-07-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_utilisateur_epreuve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='epreuve',
        ),
    ]
