# Generated by Django 5.0.6 on 2024-07-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='epreuve',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
