# Generated by Django 5.0.6 on 2024-07-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_utilisateur_epreuve_alter_utilisateur_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='epreuve',
        ),
    ]
