# Generated by Django 5.0.6 on 2024-07-29 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_delete_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.epreuve')),
            ],
        ),
    ]
