# Generated by Django 5.0.6 on 2024-07-29 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_acheter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acheter',
            name='acheteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acheter',
            name='epreuve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.epreuve'),
        ),
    ]
