# Generated by Django 5.0.6 on 2024-07-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_acheter_acheteur_alter_acheter_epreuve'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheter',
            name='date_consultation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
