# Generated by Django 5.0.6 on 2024-07-29 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_achetercorrect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achetercorrect',
            name='epreuve',
        ),
        migrations.AddField(
            model_name='achetercorrect',
            name='correction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.correction'),
        ),
    ]
